# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juan López Salar
title: Desarrollador Business Intelligence
email: ju.lopsalar@gmail.com
website: https://github.com/julopsalar/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  julopsalar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: juan-lopezs
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mí
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Soy graduado en Ingeniería Informática, trabajando actualmente en el sector del <mark>Business Intelligence</mark>. 
  
  Aunque hasta ahora mi puesto se ha centrado exclusivamente en el desarrollo de procesos de transformación de datos, también tengo gran inquietud por la rama de visualización de los Datos. Como prueba de esto, en mi Github destaco un par de proyectos de análisis de datos en torno al fútbol como fuente de datos (un visualizador  sobre las principales competiciones femeninas; y un proyecto más reciente de visualización de datos físicos sobre la reciente Eurocopa masculina).

  En este momento, me encuentro buscando un cambio laboral, en la búsqueda de algo más general respecto a la exclusiva generación y modificación de procesos ETL, valorando fundamentalmente la adición de visualización de datos (un cargo más amplio, Analista de Datos)
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Clash Royale Data Scraping
        link: github.com/julopsalar
        # link_text: Project Website
        additional_links:
          - title:  julopsalar/cr-data-mining
            icon: fab fa-github
            url: github.com/julopsalar/cr-data-mining
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Uno de mis primeros proyectos de programación. Fue también una excusa para profundizar en el lenguaje <mark>Python</mark>, y familiarizarme con el uso y acceso a APIs (tanto un cliente oficial de la desarrolladora del videojuego como un wrapper desarrollado por parte de la comunidad). 
          El uso principal consiste en trackear las batallas de ciertas cuentas del videojuego móvil <i>Clash Royale</i>. Era una forma de personalizar el acceso a configuraciones y estrategias del juego, inspirado en webs como RoyaleAPI y StatsRoyale, muy famosas en su dia.
          

          En aquel momento, usaba <mark>dashboards</mark> desarrollados en <mark>Excel</mark> (Google Sheets), en el que compartir información con otros jugadores.  
        
          # I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. 
          # I have learned many skills through this and been I'm very proud of having this in my portfolio. 
          # If you don't have a project as awesome as this I would advise you make one.

  - title: Experiencia laboral # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MetaEnlace Sistemas de Información
        link: https://metaenlace.com/
        # link_text: boringcompany.com
        sub_title: Desarrollador BI
        caption: Enero 2023 - Present
        quote: >
          Diseño e implantación de procesos ETL
        description: | # this will include new lines to allow paragraphs
          Desarrollo de procesos guiados por requisitos, utilizando la suite de <mark>Informatica Powercenter</mark>. Implementación y configuración de workflows mediante la tecnología de optimización Full PushDown.
          
          Acceso a diferentes sistemas de bases de datos (Teradata, Oracle, Microsoft SQL Server).
            
  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Murcia
        caption: 2018 - 2022
        sub_title: Graduado en Ingeniería Informática
        quote: >
          La Universidad de Murcia es una institución referente a nivel nacional, tanto a nivel educativo como a nivel investigación.
        description: | # this will include new lines to allow paragraphs
          Mención en Ciencias de la Computación
          
        # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        # I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Mis cosas
    layout: text
    content: | # this will include new lines to allow paragraphs
      .
    # Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    # - Rock climbing

    # Look at this cool image  
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
